# Name of your page (this will show up at the top of your page and in the RSS feed)
title: Car4Tegra ClassCreator

# Short description (goes below the title; it will also be used in the RSS feed)
description: Creates code files based on customizable templates

theme: jekyll-theme-slate